#!/usr/bin/env bash
# ====================
# {{scriptDescription}}
#
# @runtime Bash 4.0+
# @generated by skill-creator
#
# 使用方法:
#   ./{{scriptName}}.sh {{argsUsage}}
#
# 終了コード:
#   0: 成功
#   1: 一般エラー
#   2: 引数エラー
#   3: ファイル不在
#   4: 検証失敗
# ====================

set -euo pipefail

# ====================
# 定数
# ====================
readonly EXIT_SUCCESS=0
readonly EXIT_ERROR=1
readonly EXIT_ARGS_ERROR=2
readonly EXIT_FILE_NOT_FOUND=3
readonly EXIT_VALIDATION_FAILED=4

# カラー出力
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[0;33m'
readonly NC='\033[0m'

# スクリプトディレクトリ
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# AIへの指示: スクリプト固有の定数をここに追加


# ====================
# ログ関数
# ====================
log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# ====================
# ヘルプ表示
# ====================
# AIへの指示: Usage, Options, 説明を記述
show_help() {
  cat << EOF
{{scriptDescription}}

Usage:
  $(basename "$0") [OPTIONS]

Options:
  --input <path>   入力パス（必須）
  --output <path>  出力パス
  -h, --help       ヘルプ表示

EOF
}

# ====================
# 引数パース
# ====================
# AIへの指示: 必要な引数を追加・修正
parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --input)
        INPUT="$2"
        shift 2
        ;;
      --output)
        OUTPUT="$2"
        shift 2
        ;;
      -h|--help)
        show_help
        exit $EXIT_SUCCESS
        ;;
      *)
        log_error "不明なオプション: $1"
        exit $EXIT_ARGS_ERROR
        ;;
    esac
  done
}

# ====================
# 検証関数
# ====================
# AIへの指示: 入力検証を実装
validate_input() {
  # 必須引数チェック
  # ファイル存在チェック
  # 形式チェック
  :
}

# ====================
# メイン処理
# ====================
# AIへの指示: 以下の構造でメイン処理を実装してください
# 1. 引数パース
# 2. 入力検証
# 3. メイン処理
# 4. 出力
# 5. 終了コード返却

main() {
  parse_args "$@"
  validate_input

  # AIへの指示: メインロジックを実装
  # - エラーハンドリングを適切に行う
  # - 成功時は明確なメッセージを出力
  # - 失敗時は適切な終了コードを返す

  log_info "完了"
  exit $EXIT_SUCCESS
}

# ====================
# エントリポイント
# ====================
main "$@"
