"""render-dependency-graph.py の純関数 + main CLI 契約を network 無しで網羅する。

render-dependency-graph.py は CapabilityBundle(plugin-composition.yaml)を読み込み、
capabilities[] / dependencies[] を Mermaid `graph LR` に変換する純レンダラであり、
実通信は一切しない。よって本テストは:

  - classify: skill+ref-* 再分類 / 非 skill はそのまま
  - node_id: 安全化 / 空入力フォールバック
  - node_label: hook: 形式そのまま / パス末尾セグメント
  - render_mermaid: capabilities ノード集合 / dependencies からの補完
    (hook:/agents//commands//ref-/既定 skill)/ subgraph / edge(type 既定 calls)/
    src・dst 欠落 skip / classDef・class 割当 / 空 bundle / name 既定
  - wrap_markdown: フェンス付き Markdown
  - _self_test_path: parents[3]/plugin-composition.yaml を指す
  - _load_yaml: PyYAML 経路(インストール済)
  - main: --self-test / --bundle / どちらも無し(exit2)/ 存在しない bundle(exit1)/
    --out 書き出し / --raw / stdout 出力

を tmp_path 上の実 YAML で genuine に assert する(repo 非汚染)。
"""
import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = (
    ROOT
    / "plugins"
    / "harness-creator"
    / "skills"
    / "run-build-skill"
    / "scripts"
    / "render-dependency-graph.py"
)
SELF_TEST_BUNDLE = ROOT / "plugins" / "harness-creator" / "plugin-composition.yaml"

_SPEC = importlib.util.spec_from_file_location("render_dep_graph_under_test", SCRIPT)
MOD = importlib.util.module_from_spec(_SPEC)
_SPEC.loader.exec_module(MOD)


# --------------------------------------------------------------------------
# classify
# --------------------------------------------------------------------------

def test_classify_skill_ref_prefix_reclassified_to_ref():
    assert MOD.classify("skill", "skills/ref-output-routing") == "ref"


def test_classify_plain_skill_stays_skill():
    assert MOD.classify("skill", "skills/run-build-skill") == "skill"


def test_classify_non_skill_kinds_passthrough():
    assert MOD.classify("agent", "agents/foo") == "agent"
    assert MOD.classify("hook", "hook:Stop/Guard") == "hook"
    # kind=skill でない限り ref- prefix でも再分類しない。
    assert MOD.classify("command", "commands/ref-thing") == "command"


# --------------------------------------------------------------------------
# node_id
# --------------------------------------------------------------------------

def test_node_id_replaces_unsafe_chars():
    assert MOD.node_id("skills/run-build-skill") == "n_skills_run_build_skill"


def test_node_id_hook_form():
    assert MOD.node_id("hook:Stop/Guard") == "n_hook_Stop_Guard"


def test_node_id_empty_fallback():
    assert MOD.node_id("") == "n_unknown"
    assert MOD.node_id("///") == "n_unknown"


# --------------------------------------------------------------------------
# node_label
# --------------------------------------------------------------------------

def test_node_label_uses_last_segment():
    assert MOD.node_label("skills/run-build-skill") == "run-build-skill"


def test_node_label_hook_kept_verbatim():
    assert MOD.node_label("hook:PreToolUse/Guard") == "hook:PreToolUse/Guard"


def test_node_label_no_slash_returns_self():
    assert MOD.node_label("solo") == "solo"


# --------------------------------------------------------------------------
# _load_yaml (PyYAML 経路: インストール済前提)
# --------------------------------------------------------------------------

def test_load_yaml_parses_mapping():
    data = MOD._load_yaml("name: demo\ncapabilities:\n  - { kind: skill, ref: skills/a }\n")
    assert data["name"] == "demo"
    assert data["capabilities"][0]["ref"] == "skills/a"


def test_load_yaml_empty_returns_empty_dict():
    assert MOD._load_yaml("") == {}


# --------------------------------------------------------------------------
# render_mermaid
# --------------------------------------------------------------------------

def test_render_mermaid_basic_nodes_edges_and_styles():
    bundle = {
        "name": "demo",
        "capabilities": [
            {"kind": "skill", "ref": "skills/run-build-skill"},
            {"kind": "skill", "ref": "skills/ref-output-routing"},  # → ref に再分類
            {"kind": "agent", "ref": "agents/builder"},
        ],
        "dependencies": [
            {"from": "skills/run-build-skill", "to": "agents/builder", "type": "calls"},
        ],
    }
    out = MOD.render_mermaid(bundle)
    assert out.startswith("%% Generated by render-dependency-graph.py — bundle: demo")
    assert "graph LR" in out
    # subgraph がカテゴリごとに切られる。
    assert "subgraph skills[skill]" in out
    assert "subgraph refs[ref]" in out
    assert "subgraph agents[agent]" in out
    # エッジ。
    assert "n_skills_run_build_skill -- calls --> n_agents_builder" in out
    # classDef がカテゴリ分出る。
    for cat in MOD.STYLE:
        assert f"classDef {cat} " in out
    # class 割当(ノードが存在するカテゴリのみ)。
    assert "class n_agents_builder agent;" in out


def test_render_mermaid_completes_nodes_from_dependencies():
    # capabilities に無い ref を dependencies の from/to から補完し、prefix で kind 推定。
    bundle = {
        "name": "infer",
        "capabilities": [],
        "dependencies": [
            {"from": "skills/main", "to": "agents/sub", "type": "calls"},
            {"from": "skills/main", "to": "commands/cmd", "type": "calls"},
            {"from": "skills/main", "to": "hook:Stop/Guard", "type": "calls"},
            {"from": "skills/main", "to": "skills/ref-helper", "type": "reads"},
        ],
    }
    out = MOD.render_mermaid(bundle)
    # 各推定カテゴリが subgraph に現れる。
    assert "subgraph agents[agent]" in out
    assert "subgraph commands[command]" in out
    assert "subgraph hooks[hook]" in out
    assert "subgraph refs[ref]" in out  # skills/ref-* → ref
    assert "subgraph skills[skill]" in out  # skills/main → skill 既定
    # hook ノードラベルは hook: 形式のまま。
    assert '["hook:Stop/Guard"]' in out
    # type=reads エッジ。
    assert "-- reads --> n_skills_ref_helper" in out


def test_render_mermaid_default_edge_type_is_calls():
    bundle = {
        "name": "d",
        "capabilities": [{"kind": "skill", "ref": "skills/a"}],
        "dependencies": [{"from": "skills/a", "to": "skills/b"}],  # type 欠落
    }
    out = MOD.render_mermaid(bundle)
    assert "-- calls --> n_skills_b" in out


def test_render_mermaid_skips_edges_with_missing_endpoints():
    bundle = {
        "name": "d",
        "capabilities": [{"kind": "skill", "ref": "skills/a"}],
        "dependencies": [
            {"from": "skills/a", "to": ""},   # dst 欠落 → skip
            {"from": "", "to": "skills/a"},   # src 欠落 → skip
        ],
    }
    out = MOD.render_mermaid(bundle)
    assert "-->" not in out  # エッジは 1 本も出ない。


def test_render_mermaid_skips_capabilities_with_blank_ref():
    bundle = {
        "name": "d",
        "capabilities": [
            {"kind": "skill", "ref": ""},
            {"kind": "skill", "ref": "   "},
            {"kind": "skill", "ref": "skills/keep"},
        ],
        "dependencies": [],
    }
    out = MOD.render_mermaid(bundle)
    assert "n_skills_keep" in out
    # 空 ref はノード化されない(skill subgraph に keep だけ)。
    assert out.count('["') == 1


def test_render_mermaid_empty_bundle_uses_unknown_name():
    out = MOD.render_mermaid({})
    assert "bundle: (unknown)" in out
    assert "graph LR" in out
    # ノードもエッジも無い。
    assert "subgraph" not in out
    assert "-->" not in out


def test_render_mermaid_none_lists_treated_as_empty():
    # capabilities/dependencies が None でも空扱い(`or []`)。
    out = MOD.render_mermaid({"name": "n", "capabilities": None, "dependencies": None})
    assert "subgraph" not in out


# --------------------------------------------------------------------------
# wrap_markdown
# --------------------------------------------------------------------------

def test_wrap_markdown_fences_mermaid():
    md = MOD.wrap_markdown("graph LR\n", "Title")
    assert md.startswith("# Dependency Graph: Title")
    assert "```mermaid\ngraph LR\n```" in md


# --------------------------------------------------------------------------
# _self_test_path
# --------------------------------------------------------------------------

def test_self_test_path_points_at_plugin_composition():
    p = MOD._self_test_path()
    assert p == SELF_TEST_BUNDLE.resolve()
    assert p.name == "plugin-composition.yaml"


# --------------------------------------------------------------------------
# main(): 関数を直接呼ぶ経路 (argv 渡し)
# --------------------------------------------------------------------------

def test_main_requires_bundle_or_self_test(capsys):
    # どちらの引数も無いと argparse.error → SystemExit(2)。
    with pytest.raises(SystemExit) as ei:
        MOD.main([])
    assert ei.value.code == 2
    err = capsys.readouterr().err
    assert "--bundle" in err and "--self-test" in err


def test_main_bundle_not_found_returns_1(tmp_path, capsys):
    rc = MOD.main(["--bundle", str(tmp_path / "nope.yaml")])
    assert rc == 1
    assert "bundle not found" in capsys.readouterr().err


def test_main_self_test_renders_to_stdout(capsys):
    rc = MOD.main(["--self-test"])
    assert rc == 0
    out = capsys.readouterr().out
    assert "graph LR" in out
    assert "```mermaid" in out  # markdown 既定
    # self-test bundle 名がタイトルに反映。
    assert "# Dependency Graph: harness-creator" in out


def test_main_raw_flag_omits_markdown_fence(capsys):
    rc = MOD.main(["--self-test", "--raw"])
    assert rc == 0
    out = capsys.readouterr().out
    assert "graph LR" in out
    assert "```mermaid" not in out  # raw はフェンス無し
    assert not out.startswith("# Dependency Graph")


def test_main_inprocess_out_writes_file_and_makes_parent(tmp_path, capsys):
    # --out 経路(親 mkdir + write + [ok] 出力)を in-process で計測対象に乗せる。
    bundle = _bundle_yaml(tmp_path)
    out_file = tmp_path / "deep" / "nested" / "graph.md"
    rc = MOD.main(["--bundle", str(bundle), "--out", str(out_file)])
    assert rc == 0
    assert out_file.exists()
    body = out_file.read_text(encoding="utf-8")
    assert "graph LR" in body and "```mermaid" in body
    assert "[ok] wrote" in capsys.readouterr().out


def test_main_inprocess_bundle_path_resolved(tmp_path, capsys):
    # --bundle 指定経路(self-test でない側の bundle_path 解決)を踏む。
    bundle = _bundle_yaml(tmp_path)
    rc = MOD.main(["--bundle", str(bundle)])
    assert rc == 0
    out = capsys.readouterr().out
    assert "# Dependency Graph: tmpbundle" in out
    assert "n_skills_run_a -- calls --> n_agents_helper" in out


# --------------------------------------------------------------------------
# main(): subprocess 経路 (CLI 契約 + --out 書き出し)
# --------------------------------------------------------------------------

def _bundle_yaml(tmp_path):
    p = tmp_path / "plugin-composition.yaml"
    p.write_text(
        "name: tmpbundle\n"
        "capabilities:\n"
        "  - { kind: skill, ref: skills/run-a }\n"
        "  - { kind: agent, ref: agents/helper }\n"
        "dependencies:\n"
        "  - { from: skills/run-a, to: agents/helper, type: calls }\n",
        encoding="utf-8",
    )
    return p


def _run(args, cwd):
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True, text=True, cwd=cwd,
    )


def test_cli_help_exit0(tmp_path):
    proc = _run(["--help"], cwd=str(tmp_path))
    assert proc.returncode == 0
    assert "--bundle" in proc.stdout and "--self-test" in proc.stdout


def test_cli_bundle_to_stdout(tmp_path):
    bundle = _bundle_yaml(tmp_path)
    proc = _run(["--bundle", str(bundle)], cwd=str(tmp_path))
    assert proc.returncode == 0, proc.stderr
    assert "graph LR" in proc.stdout
    assert "n_skills_run_a -- calls --> n_agents_helper" in proc.stdout
    assert "# Dependency Graph: tmpbundle" in proc.stdout


def test_cli_bundle_out_writes_file(tmp_path):
    bundle = _bundle_yaml(tmp_path)
    out_file = tmp_path / "nested" / "graph.md"
    proc = _run(["--bundle", str(bundle), "--out", str(out_file)], cwd=str(tmp_path))
    assert proc.returncode == 0, proc.stderr
    assert out_file.exists()  # 親ディレクトリも作成される。
    body = out_file.read_text(encoding="utf-8")
    assert "graph LR" in body and "```mermaid" in body
    assert f"[ok] wrote {out_file.resolve()}" in proc.stdout


def test_cli_raw_out_has_no_fence(tmp_path):
    bundle = _bundle_yaml(tmp_path)
    out_file = tmp_path / "graph.mmd"
    proc = _run(["--bundle", str(bundle), "--out", str(out_file), "--raw"],
                cwd=str(tmp_path))
    assert proc.returncode == 0, proc.stderr
    body = out_file.read_text(encoding="utf-8")
    assert "graph LR" in body
    assert "```mermaid" not in body


def test_cli_missing_args_exit2(tmp_path):
    proc = _run([], cwd=str(tmp_path))
    assert proc.returncode == 2
    assert "--bundle" in proc.stderr or "usage" in proc.stderr.lower()


def test_cli_bundle_not_found_exit1(tmp_path):
    proc = _run(["--bundle", str(tmp_path / "missing.yaml")], cwd=str(tmp_path))
    assert proc.returncode == 1
    assert "bundle not found" in proc.stderr


def test_cli_self_test_runs(tmp_path):
    proc = _run(["--self-test"], cwd=str(tmp_path))
    assert proc.returncode == 0, proc.stderr
    assert "# Dependency Graph: harness-creator" in proc.stdout
