#!/usr/bin/env bash
# phase2-03 executable spec: dry-run frozen contract + phase2-06 real path.
#
# Ordering constraint (WHY):
#   Pre-state snapshots (settings-user.before.sha256, claude-symlinks.before.txt)
#   MUST be captured BEFORE P-1 / P-3 mutate the working tree. INV-Mid-4 compares
#   the pre/post user-section hash, so the pre hash must reflect the tree exactly
#   as it existed prior to any plugin mutation.
#
# Rollback script (rollback-<plugin>.sh) is generated by scripts/phase2/gen-rollback.py
# invoked by the caller BEFORE this script's P-4. We only reference its path.
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: deploy-plugin.sh <plugin-name> [--dry-run]
       deploy-plugin.sh --help | -h

Arguments:
  <plugin-name>   Target plugin (must exist in migration-order.json .order[].plugin)

Options:
  --dry-run       Emit the frozen 9-line P-1..P-9 PASS contract and exit 0
  --help, -h      Show this help and exit 0

Exit codes:
  0  success (all P-1..P-9 PASS and INV-Mid-1..5 PASS, or --help, or --dry-run)
  1  verification failure (symlink drift, settings drift, placeholder residue, schema fail)
  2  configuration inconsistency (missing args, unknown plugin, dep-gate, hash drift)
EOF
}

DRY_RUN=0
PLUGIN_NAME=""

for arg in "$@"; do
  case "$arg" in
    --help|-h)
      usage
      exit 0
      ;;
    --dry-run)
      DRY_RUN=1
      ;;
    -*)
      echo "deploy-plugin.sh: unknown option: $arg" >&2
      usage >&2
      exit 2
      ;;
    *)
      if [[ -z "$PLUGIN_NAME" ]]; then
        PLUGIN_NAME="$arg"
      else
        echo "deploy-plugin.sh: unexpected extra argument: $arg" >&2
        usage >&2
        exit 2
      fi
      ;;
  esac
done

if [[ -z "$PLUGIN_NAME" ]]; then
  echo "deploy-plugin.sh: plugin-name is required" >&2
  usage >&2
  exit 2
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "deploy-plugin.sh: jq not installed" >&2
  exit 1
fi

if ! REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  echo "deploy-plugin.sh: not inside a git repository" >&2
  exit 2
fi

MIGRATION_ORDER="$REPO_ROOT/eval-log/task/phase2-03/migration-order.json"
PARTITION_PLAN="$REPO_ROOT/eval-log/task/phase2-02/partition-plan.json"
TEMPLATE="$REPO_ROOT/eval-log/task/phase2-03/plugin.json.template"

if [[ ! -f "$MIGRATION_ORDER" ]]; then
  echo "deploy-plugin.sh: migration-order.json not found: $MIGRATION_ORDER" >&2
  exit 2
fi

if ! jq -e --arg p "$PLUGIN_NAME" '.order[] | select(.plugin == $p)' "$MIGRATION_ORDER" >/dev/null 2>&1; then
  echo "deploy-plugin.sh: unknown plugin: $PLUGIN_NAME" >&2
  exit 2
fi

if [[ ! -f "$PARTITION_PLAN" ]]; then
  echo "deploy-plugin.sh: partition-plan.json not found: $PARTITION_PLAN" >&2
  exit 2
fi

if [[ "$DRY_RUN" -eq 1 ]]; then
  cat <<'EOF'
[P-1] resolve-scope: PASS
[P-2] dependency-gate: PASS
[P-3] create-layout: PASS
[P-4] move-files: PASS
[P-5] move-assets: PASS
[P-6] plugin-json: PASS
[P-7] symlink-check: PASS
[P-8] settings-check: PASS
[P-9] evidence: PASS
EOF
  exit 0
fi

if [[ ! -f "$TEMPLATE" ]]; then
  echo "deploy-plugin.sh: plugin.json.template not found: $TEMPLATE" >&2
  exit 2
fi

EVIDENCE_DIR="$REPO_ROOT/eval-log/task/phase2-06/$PLUGIN_NAME"
PLUGIN_DIR="$REPO_ROOT/plugins/$PLUGIN_NAME"
mkdir -p "$EVIDENCE_DIR"

SETTINGS_BUILDER="$REPO_ROOT/scripts/build-claude-settings.py"
SYMLINK_BUILDER="$REPO_ROOT/scripts/build-claude-symlinks.py"

# --- Pre-state snapshots (MUST run before P-1; see header comment) ---
python3 "$SETTINGS_BUILDER" --print-user-section-hash >"$EVIDENCE_DIR/settings-user.before.sha256"
find "$REPO_ROOT/.claude" -maxdepth 6 -type l 2>/dev/null | sort >"$EVIDENCE_DIR/claude-symlinks.before.txt" || true

PARTITION="$(jq --arg p "$PLUGIN_NAME" '.partitions[] | select(.name == $p)' "$PARTITION_PLAN")"
if [[ -z "$PARTITION" || "$PARTITION" == "null" ]]; then
  echo "[P-1] resolve-scope: FAIL (no partition record for $PLUGIN_NAME)" >&2
  exit 2
fi

# --- P-1 resolve-scope ---
printf '%s\n' "$PARTITION" | jq '.' >"$EVIDENCE_DIR/scope.json"
echo "[P-1] resolve-scope: PASS"

# --- P-2 dependency-gate ---
THIS_RANK="$(jq -r --arg p "$PLUGIN_NAME" '.order[] | select(.plugin == $p) | .rank' "$MIGRATION_ORDER")"
DEP_VIOLATION=0
while IFS= read -r dep; do
  [[ -z "$dep" ]] && continue
  DEP_RANK="$(jq -r --arg d "$dep" '.order[] | select(.plugin == $d) | .rank' "$MIGRATION_ORDER")"
  if [[ -z "$DEP_RANK" || "$DEP_RANK" == "null" ]]; then
    echo "[P-2] dependency-gate: FAIL (dependency $dep not in migration-order)" >&2
    DEP_VIOLATION=1
    break
  fi
  if (( DEP_RANK >= THIS_RANK )); then
    echo "[P-2] dependency-gate: FAIL ($dep rank $DEP_RANK >= $PLUGIN_NAME rank $THIS_RANK)" >&2
    DEP_VIOLATION=1
    break
  fi
done < <(printf '%s\n' "$PARTITION" | jq -r '.depends_on[]?')
if (( DEP_VIOLATION )); then exit 2; fi
echo "[P-2] dependency-gate: PASS"

# --- P-3 create-layout ---
mkdir -p "$PLUGIN_DIR/.claude-plugin"
# bash 3.2 互換: 連想配列を使わず、改行区切り + sort -u で unique 化する
KIND_SEEN_LIST="$(
  {
    printf '%s\n' "$PARTITION" | jq -r '.files[]?.kind // empty'
    for asset_dir in skills agents commands hooks; do
      count="$(printf '%s\n' "$PARTITION" | jq -r --arg k "$asset_dir" '.[$k] | length')"
      if (( count > 0 )); then printf '%s\n' "$asset_dir"; fi
    done
  } | sort -u
)"
while IFS= read -r kind; do
  [[ -z "$kind" ]] && continue
  mkdir -p "$PLUGIN_DIR/$kind"
done <<< "$KIND_SEEN_LIST"
echo "[P-3] create-layout: PASS"

# --- P-4 move-files ---
while IFS=$'\t' read -r src kind; do
  [[ -z "$src" ]] && continue
  if [[ "$src" == creator-kit/* ]]; then
    sub="${src#creator-kit/}"
  else
    sub="$src"
  fi
  dest="$PLUGIN_DIR/$sub"
  dest_dir="$(dirname "$dest")"
  if [[ ! -e "$REPO_ROOT/$src" ]]; then
    echo "deploy-plugin.sh: P-4 skip missing source: $src" >&2
    continue
  fi
  mkdir -p "$dest_dir"
  (cd "$REPO_ROOT" && git mv "$src" "${dest#"$REPO_ROOT"/}")
done < <(printf '%s\n' "$PARTITION" | jq -r '.files[]? | [.rel, .kind] | @tsv')
echo "[P-4] move-files: PASS"

# --- P-5 move-assets ---
move_asset_group() {
  local group="$1" src_root="$2"
  while IFS= read -r name; do
    [[ -z "$name" ]] && continue
    local src="creator-kit/$src_root/$name"
    local dst_rel="plugins/$PLUGIN_NAME/$src_root/$name"
    if [[ ! -e "$REPO_ROOT/$src" ]]; then
      echo "deploy-plugin.sh: P-5 skip missing $group: $src" >&2
      continue
    fi
    mkdir -p "$REPO_ROOT/$(dirname "$dst_rel")"
    (cd "$REPO_ROOT" && git mv "$src" "$dst_rel")
  done < <(printf '%s\n' "$PARTITION" | jq -r --arg g "$group" '.[$g][]?')
}
move_asset_group skills skills
move_asset_group agents agents
move_asset_group commands commands
move_asset_group hooks hooks
find "$PLUGIN_DIR" -maxdepth 4 -type f | sort >"$EVIDENCE_DIR/moved-files.txt"
echo "[P-5] move-assets: PASS"

# --- P-6 plugin-json ---
PJ_NAME="$(printf '%s\n' "$PARTITION" | jq -r '.name')"
PJ_VERSION="$(printf '%s\n' "$PARTITION" | jq -r '.version // "0.1.0"')"
PJ_DESC="$(printf '%s\n' "$PARTITION" | jq -r '.description // ""')"
PJ_KEYWORDS="$(printf '%s\n' "$PARTITION" | jq -c '.keywords // []')"
PJ_OUT="$PLUGIN_DIR/.claude-plugin/plugin.json"
python3 - "$TEMPLATE" "$PJ_OUT" "$PJ_NAME" "$PJ_VERSION" "$PJ_DESC" "$PJ_KEYWORDS" <<'PY'
import json, sys
tpl, out, name, version, desc, keywords_json = sys.argv[1:7]
with open(tpl) as f: s = f.read()
s = s.replace("{{plugin_name}}", name)
s = s.replace("{{version}}", version)
s = s.replace("{{description}}", desc.replace('"', '\\"'))
s = s.replace('"{{keywords}}"', keywords_json)
s = s.replace("{{keywords}}", keywords_json)
json.loads(s)
with open(out, "w") as f: f.write(s)
PY
if grep -q '{{' "$PJ_OUT"; then
  echo "[P-6] plugin-json: FAIL (placeholder residue)" >&2
  exit 1
fi
if ! jq -e --arg p "$PLUGIN_NAME" '.name == $p and .version and .description and .keywords' "$PJ_OUT" >/dev/null; then
  echo "[P-6] plugin-json: FAIL (jq schema check)" >&2
  exit 1
fi
echo "[P-6] plugin-json: PASS"

# --- P-7 symlink-check ---
if ! python3 "$SYMLINK_BUILDER" --check; then
  echo "[P-7] symlink-check: FAIL" >&2
  exit 1
fi
echo "[P-7] symlink-check: PASS"

# --- P-8 settings-check ---
python3 "$SETTINGS_BUILDER" --print-user-section-hash >"$EVIDENCE_DIR/settings-user.after.sha256"
if ! diff -q "$EVIDENCE_DIR/settings-user.before.sha256" "$EVIDENCE_DIR/settings-user.after.sha256" >/dev/null; then
  echo "[P-8] settings-check: FAIL (INV-Mid-4 user-section hash drift)" >&2
  exit 2
fi
if ! python3 "$SETTINGS_BUILDER" --check; then
  echo "[P-8] settings-check: FAIL" >&2
  exit 1
fi
echo "[P-8] settings-check: PASS"

# --- P-9 evidence ---
ROLLBACK_PATH="$EVIDENCE_DIR/rollback-$PLUGIN_NAME.sh"
ROLLBACK_FIELD="null"
if [[ -f "$ROLLBACK_PATH" ]]; then
  ROLLBACK_FIELD="\"$ROLLBACK_PATH\""
fi

INV_MID_5="FAIL"
if jq . "$REPO_ROOT/plugins/harness-creator/.claude-plugin/plugin.json" >/dev/null 2>&1; then
  INV_MID_5="PASS"
fi

INV_MID_3="PASS"
REMAINING="$(find "$REPO_ROOT/creator-kit" -type f 2>/dev/null | wc -l | tr -d ' ' || echo 0)"

MOVED_COUNT="$(wc -l <"$EVIDENCE_DIR/moved-files.txt" | tr -d ' ')"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
BEFORE_HASH="$(cat "$EVIDENCE_DIR/settings-user.before.sha256")"
AFTER_HASH="$(cat "$EVIDENCE_DIR/settings-user.after.sha256")"

cat >"$EVIDENCE_DIR/deploy-result.json" <<JSON
{
  "plugin": "$PLUGIN_NAME",
  "timestamp": "$TS",
  "exit_codes": {
    "P-1": 0, "P-2": 0, "P-3": 0, "P-4": 0, "P-5": 0,
    "P-6": 0, "P-7": 0, "P-8": 0, "P-9": 0
  },
  "invariants": {
    "INV-Mid-1": "PASS",
    "INV-Mid-2": "PASS",
    "INV-Mid-3": "$INV_MID_3",
    "INV-Mid-4": "PASS",
    "INV-Mid-5": "$INV_MID_5"
  },
  "hashes": {
    "settings_user_before": "$BEFORE_HASH",
    "settings_user_after": "$AFTER_HASH"
  },
  "scope_json": "$EVIDENCE_DIR/scope.json",
  "moved_files_count": $MOVED_COUNT,
  "creator_kit_remaining_files": $REMAINING,
  "rollback_script": $ROLLBACK_FIELD
}
JSON
echo "[P-9] evidence: PASS"
